### ISSUE TITLE
Create support for Swift package manager

### ISSUE THREAD

**Issue by shvets** [scinfu/SwiftSoup#1]
It misses Package.swift file:

import PackageDescription

let package = Package(
  name: "SwiftSoup"
)

and Test has to be renamed to SwiftSoupTests.

**Comment by scinfu** [comment]
ToDo.
Using Package.swift make the build have errors , i'm working to fix this problem

**Comment by scinfu** [comment]
All requests are done.

**Comment by scinfu** [comment]
I close the issue , if needed reopen it.
