### ISSUE TITLE
SwiftSoup not building on Swift-Linux 4.2

### ISSUE THREAD

**Issue by hactar** [scinfu/SwiftSoup#101]
When trying to build a project that includes SwiftSoup on Swift-Linux 4.2, the compilation fails:

```
1.	While verifying SIL function "@$S9SwiftSoup4NodeC16OuterHtmlVisitor33_88DB12878250A47CDE78A89F4976DAEELLC4tailyyAC_SitKF".
 for 'tail(_:_:)' at /root/project/.build-ubuntu/checkouts/SwiftSoup.git--3976131514847736029/Sources/Node.swift:752:14
<unknown>:0: error: unable to execute command: Aborted
<unknown>:0: error: compile command failed due to signal 6 (use -v to see invocation)
```

This appears to be happening on SwiftSoups own TravisCI too:

https://travis-ci.org/scinfu/SwiftSoup/jobs/438795328

**Comment by 0xTim** [comment]
Looks like this PR broke it - the tests were failing when the PR was merged.

Can we not merge PRs that fail CI? It kinda defeats the point of having CI if you ignore the results and breaks it for people like above

**Comment by 0xTim** [comment]
Didn't link the PR! It was this one - https://github.com/scinfu/SwiftSoup/pull/97/

That set the swift tools version to 4.2. The Dockerfile is pulling in `swift:latest` so when 4.2 was released it used that.

Having said that, there has been an issue raised with Vapor as well for old Vapor 2 code failing to compile on Linux in release mode. People are looking at it

**Comment by hactar** [comment]
Ah, cool, yeah. 

I think I've found a workaround (removing the "saves a void hit." optimization) - doing a few more tests. I'm not sure why it solves the problem as the code looks good, but it might be a workaround until the issue can be properly resolved.
