### ISSUE TITLE
Newlines being inserted in HTML output.

### ISSUE THREAD

**Issue by zac-garby** [scinfu/SwiftSoup#113]
If I parse this document and store it in a variable called `doc`:

```html
<h2 id=item></h2>
<h3 id=module></h3>
<h3 id=package></h3>
```

And then run the following code:

```swift
doc.select("#item").first()!.html("<b>module</b> Data.<span class=name><s0>Map</s0></span>")
```

It produces the following output (from `doc.description`):

```html
<html>
 <head></head>
 <body>
  <h2 id="item"><b>module</b> Data.<span class="name">
    <s0>
     Map
    </s0></span></h2>
  <h3 id="module"></h3>
  <h3 id="package">containers</h3>
 </body>
</html>
```

The problem here is that the contents of the `<s0>` tag have been moved onto a separate line, which causes a space to be rendered between `Data.` and `Map` when I render the HTML (using WebKit).

I feel like this shouldn't happen. But regardless, is there any way to get around this?

**Comment by zac-garby** [comment]
Update: If I replace the `<s0>` tags with `<span>`, the problem goes away. So I'm going to assume that this is a bug.

**Comment by scinfu** [comment]
i do not this so, s0 is parsed like a `div` tag.
