### ISSUE TITLE
SwiftSoup mobile version-website html

### ISSUE THREAD

**Issue by josipvukovic** [scinfu/SwiftSoup#114]
Hi, I'm developing mobile app for local news portal...this is their website ("www.ferata.hr"). I was wondering is there any way to get html from mobile version of this website. When I open it on safari on iPhone it still has the same link but it opens mobile version of website. Reason why I'm doing this is because mobile html has some attributes that normal website doesn't have (number of how many times each article has been open)...thanks! ;)

**Comment by scinfu** [comment]
Hi,
to retrive html from a site you use 'String(contentsOf: myURL, encoding: .utf8)'

Nabil
