### ISSUE TITLE
How would you scrape certain webpages?

### ISSUE THREAD

**Issue by tetrahed** [scinfu/SwiftSoup#118]
When I tried scraping websites like this link from the Hill (https://thehill.com/homenews/media/454838-cnn-announces-climate-town-hall-with-2020-democrats) or from CNN (https://www.cnn.com/2019/07/25/us/colorado-missing-girl-remains-found-after-34-years/index.html) I can't seem to scrape any of the text other than the first sentence.  How should I solve this issue?

**Comment by scinfu** [comment]
can you explain better.

closed due to inactivity
If you need open again
