### ISSUE TITLE
"SwiftSoup" Sceme in Example.workspace Gets Built with Carthage 

### ISSUE THREAD

**Issue by nicolas-miari** [scinfu/SwiftSoup#122]
The "SwiftSoup" scheme in the "Example" workspace is marked as "shared", and thus gets automatically built with building Carthage dependencies, making the (already long) build unnecessarily longer.

<img width="579" alt="Screen Shot 2019-09-11 at 13 56 25" src="https://user-images.githubusercontent.com/1000912/64669332-25763000-d49c-11e9-82a1-7676045928b9.png">

<img width="447" alt="Screen Shot 2019-09-11 at 13 56 52" src="https://user-images.githubusercontent.com/1000912/64669346-32931f00-d49c-11e9-85a6-006a26a697d0.png">

...or is it needed for CI purposes?

**Comment by scinfu** [comment]
Did you open Example/Example.xcworkspace ?
It's not flagged shared.

> ...or is it needed for CI purposes?
I'm removing it, let know if problem persists

**Comment by scinfu** [comment]
Fixed in 2.2.1

Can you try and let me know if the change make some problem?

**Comment by nicolas-miari** [comment]
@scinfu
Thanks, I’ll check it as soon as I get to work on Tuesday.

**Comment by aehlke** [comment]
```
*** Checking out SwiftSoup at "2.2.1"
[...]
*** Building scheme "SwiftSoup-iOS" in SwiftSoup.xcodeproj
*** Building scheme "SwiftSoup" in Example.xcworkspace
```

**Comment by aehlke** [comment]
It looks like it hangs at this point, blocking me from using SwiftSoup. Swift consumes all my CPU building this step but after a couple attempts of letting it run for tens of minutes it never finishes. Could be that I need to wait longer but I believe it ran for more than a half hour, seemingly stuck at that point.

**Comment by nicolas-miari** [comment]
@scinfu 
It seems to be working now, for me at least. Using:

    carthage update SwiftSoup --platform iOS

I get:
<img width="956" alt="Screen Shot 2019-09-24 at 12 15 17" src="https://user-images.githubusercontent.com/1000912/65478610-522b3e00-dec5-11e9-9eb4-84977e7d1396.png">

I also tried updating **all dependencies** with `$ carthage update --platform iOS` (just to be sure), and _Example.xcworkspace_ **isn't** built.

Thank you.
