### ISSUE TITLE
Can't use this in cocoapods as your ci is building failed.

### ISSUE THREAD

**Issue by owenzhao** [scinfu/SwiftSoup#123]
Is there a temporary solution?

**Comment by scinfu** [comment]
Our CI only had the xcode version not updated to 10.3 or 11, now it's the right one, 11.

What problem do you have?

Scinfu

**Comment by owenzhao** [comment]
> dyld: Library not loaded: @rpath/SwiftSoup.framework/Versions/A/SwiftSoup
  Referenced from: /Users/zhaoxin/Library/Developer/Xcode/DerivedData/HTML_Editor-fsnxjjdbzogonocgzrdxclnobasj/Build/Products/Debug/HTML Editor
  Reason: image not found

Just a command line app with nothing in it.

```swift
import Foundation
import SwiftSoup

func foo() -> String {
//    do {
//       let html = "<html><head><title>First parse</title></head>"
//           + "<body><p>Parsed HTML into a doc.</p></body></html>"
//       let doc: Document = try SwiftSoup.parse(html)
//       return try doc.text()
//    } catch Exception.Error(let type, let message) {
//        print(message)
//    } catch {
//        print("error")
//    }
    
    return ""
}

print(foo())
```

**Comment by scinfu** [comment]
@owenzhao  can you provide a demo project?

**Comment by owenzhao** [comment]
It is just a simple project. Xcode, choose new project, command line tool app.

use CocoaPods added this pod.

copy the above code to main.swfit.

**Comment by owenzhao** [comment]
You can download the sample project [here](https://zhaoxin.pro/files/html_editor.zip).

**Comment by scinfu** [comment]
Your project do not have info.plist.
Here is my test project https://gofile.io/?c=VRhXIc where compile and run without any problema.

**Comment by owenzhao** [comment]
> Your project do not have info.plist.
> Here is my test project https://gofile.io/?c=VRhXIc where compile and run without any problem.

Thank you for you reply. However, currently, a newly created project with Xcode 11 no longer uses an info plist. And it runs well if I doesn't not use CocoaPods. 

So it is my responsibility to create a info.plist or should CocoaPods does that?
