### ISSUE TITLE
SwiftSoup not being recognized by Xcode 9.2 (Cococa pods)

### ISSUE THREAD

**Issue by Merkie** [scinfu/SwiftSoup#126]
So I've been trying to get SwiftSoup to work for about the past 3 hours. I'm new to Xcode, so I may be missing something obvious - but I've gone through about every thread looking for a solution. To clarify, I am opening the .xcworkspace file. This still wont work even on a fresh Xcode project.
![Screen Shot 2019-09-29 at 3 36 13 PM](https://user-images.githubusercontent.com/18383101/65839007-ee42b400-e2ce-11e9-9abe-8bd11befa87e.png)

**Comment by scinfu** [comment]
Closed due to inactivity and because it has been solved with new xCode
