### ISSUE TITLE
Pod 'SwiftSoup' not working with macOS Catalina 10.15

### ISSUE THREAD

**Issue by alvarezac1** [scinfu/SwiftSoup#128]
I'm new to coding (taking a Udemy class on iOS Swift Development). I'm trying to add `pod 'SwiftSoup'` pod into my Xcode project. I was able to add the pod (screen shot 1) but then get an error when trying to import the pod in Xcode (screen shot 2). I've been reading on Overstackflow and still haven't found an answer. I did use the `sudo gem install cocoapods` command in terminal but still got these errors. Any guidance is much appreciated! Thanks

**Screen shot 1**
![image](https://user-images.githubusercontent.com/56129207/66797008-488e6800-eebe-11e9-91d7-82fe18f02f7a.png)

**Screen shot 2**
![image](https://user-images.githubusercontent.com/56129207/66797106-95723e80-eebe-11e9-99b7-66b669d9532a.png)

**Comment by scinfu** [comment]
Did you opened Workspace instead project?

**Comment by alvarezac1** [comment]
Hey @scinfu - yes, I opened the `.xcworkspace` file not the `. xcodeproj` file.

**Comment by scinfu** [comment]
Try last release
Thank you
