### ISSUE TITLE
Linux Swift 3.1 Build Failing

### ISSUE THREAD

**Issue by 0xTim** [scinfu/SwiftSoup#13]
SwiftSoup does not build on Linux with Swift 3.1 due to Apple helpfully renaming `RegularExpression` to `NSRegularExpression` on Linux in 3.1... I have no idea why either! I'll get a PR together which sorts this out and updates the CI scripts to run on 3.1 across everything

**Comment by scinfu** [comment]
Are you using Ubuntu?

**Comment by 0xTim** [comment]
Yeah it will be Ubuntu - here's the build failing for my project when I bumped it up to 3.1 https://travis-ci.org/brokenhandsio/SteamPress/jobs/218849023#L744

**Comment by scinfu** [comment]
fixed , try 1.3.0

**Comment by 0xTim** [comment]
Yep looks good! 👍 Would be good to get the .travis.yml file working on 3.1 so the tests are run on there as well (it's also still pointing to my forked repo's script) - do you want a PR for this?

**Comment by scinfu** [comment]
Thank you , i'm edited in VERSION="3.1" , i'm waiting travis ci to see the response

**Comment by 0xTim** [comment]
You'll need to change this line as well: https://github.com/scinfu/SwiftSoup/blob/master/.travis.yml#L13

**Comment by 0xTim** [comment]
It should read: 
`  - eval "$(curl -sL https://raw.githubusercontent.com/brokenhandsio/scinfu/master/ci)"`
Also you need to change the Xcode version to `xcode8.3` in the same file 😄

**Comment by scinfu** [comment]
Make a PR ... AHHAHA

**Comment by 0xTim** [comment]
Ha done in #14

**Comment by scinfu** [comment]
Thank you Tim

**Comment by 0xTim** [comment]
Given this is now building (and green!) again on Linux and macOS with Swift 3.1 I'm gonna close this. Thanks for the swift (aha) fix 😆
