### ISSUE TITLE
Not build for `release` in v 2.2.1

### ISSUE THREAD

**Issue by MojtabaHs** [scinfu/SwiftSoup#131]
- The build process hangs when use `release` configuration. 
- I use native SPM in Xcode.
- Build for debug worked without any issue.
- Changing Apple Clang - optimization level to `none` doesn't help
- Changing Swift Compiler - optimization level to `none` doesn't help
- Changing both to `none` doesn't help as well.

The log starts with : CompileSwift normal x86_64 (in target 'SwiftSoup' from project 'SwiftSoup')

The project is on V2.2.1

**Comment by niravbhimani53** [comment]
Duplicate of #125
