### ISSUE TITLE
attr() function getting \n 

### ISSUE THREAD

**Issue by rafaelreis-hotmart** [scinfu/SwiftSoup#136]
Hey guys, 

when I invoke attr("<meta property="og:image" content="

    https://s.glbimg.com/en/ho/static/globo_com_2016/img/home_200x200.png

">") I get ""\n\n    https://s.glbimg.com/en/ho/static/globo_com_2016/img/home_200x200.png\n\n""

There's no trim() inside that function. It's that correct ?

**Comment by scinfu** [comment]
Yes, is the content.
