### ISSUE TITLE
'Selector' is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by mspanadgoo** [scinfu/SwiftSoup#140]
I want to override canPerformAction function in my code but i get this error 
" 'Selector' is ambiguous for type lookup in this context "
because there is a class named Selector in SwiftSoup.
please change the class name. 
![Screen Shot 1398-10-29 at 17 57 35](https://user-images.githubusercontent.com/2681555/72682700-320f3280-3ae5-11ea-934b-466bac30a5ad.png)

**Comment by 0xTim** [comment]
Use `SwiftSoup.Selector`

**Comment by scinfu** [comment]
closed due to inactivity

**Comment by tristanaustin** [comment]
I just ran into this same problem. I am trying to override the NSObject function
`override open func responds(to aSelector: Selector!) -> Bool`

As soon as I import SwiftSoup, I get this error. I don't want to use the SwiftSoup one, so the recommendation above won't work for me.

For anyone else looking for a solution, the 'standard module' prefix to use is ObjectiveC in this case:

`override open func responds(to aSelector: ObjectiveC.Selector!) -> Bool`
