### ISSUE TITLE
Playground fails to run, "error: Couldn't lookup symbols:"

### ISSUE THREAD

**Issue by hxsseeb** [scinfu/SwiftSoup#143]
Does not let me compile code, was working fine yesterday however today it's giving me errors 

```
error: Couldn't lookup symbols:
  SwiftSoup.parse(Swift.String) throws -> SwiftSoup.Document
```

**Comment by scinfu** [comment]
closed due to inactivity and non-reproducibility.
If you need, repeat it by attaching a project with an example
Thank you
