### ISSUE TITLE
Strange package resolution error

### ISSUE THREAD

**Issue by barrymcbride** [scinfu/SwiftSoup#151]
Hello!

I'm getting the following error when using Swift Build to feed Docker. I'm on Swift 5:

_no versions of SwiftSoup match the requirement 2.0.0..<3.0.0 and root depends on SwiftSoup 2.0.0..<3.0.0, version solving failed_

However, when I build with XCode 11.4 everything is fine. It resolves to 2.3 as expected. This just started happening a few days ago. 

My file for SwiftSoup in package.swift looks like this:

      .package(url: "https://github.com/scinfu/SwiftSoup.git", from: "2.0.0"),

Has something changed on your end that could cause this error? I have no idea why this is happening and can't google up anything similar to use as a basis for fixing the error.

**Comment by scinfu** [comment]
Some day ago i removed ci docker but I don't understand how that file can cause problems with SPM.
How can reproduce this issue?

**Comment by barrymcbride** [comment]
Hi! Thanks for the response... I rebuilt the app from scratch and the error went away on the new app. I'm at a loss to explain it, but with a fresh start, the error went away.
