### ISSUE TITLE
outerHtml() Takes a very long time when html contains inline embedded data (esp. audio) 

### ISSUE THREAD

**Issue by triton3** [scinfu/SwiftSoup#152]
When the html contains inline data elements such as audio, `doc.outerHtml()` function takes a very long time (more than 2 mins). The inline audio is present as data in base64 format of the form:

```
<audio controls controlsList="nodownload" src="data:audio/mp4;base64,...">Audio playback is not supported. Please try with a different browser.</audio>
```

Is there something that can be done to reduce this time to extract the outer html? The audio data itself is less than a couple of MB in size.

**Comment by scinfu** [comment]
I think this is performance issue, i will work to find a solution.
