### ISSUE TITLE
HtmlTreeBuilderState isWhitespace memory leak

### ISSUE THREAD

**Issue by amecava** [scinfu/SwiftSoup#155]
I'm encountering various memory leaks during parsing.

<img width="886" alt="Screenshot 2020-04-09 at 20 16 51" src="https://user-images.githubusercontent.com/23270320/78927364-10e42f80-7a9f-11ea-9f28-563312b0fe89.png">

Thanks for the support!

**Comment by triton3** [comment]
We are seeing this memory leak as well. Any suggestion on how to fix it?

**Comment by scinfu** [comment]
do you have a demo project?

**Comment by userNameIsBoris** [comment]
Same
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/68778381/126039115-3391a826-a046-4fed-b188-50b469ec3e4e.png">
