### ISSUE TITLE
Not compiling with xcode Version 8.3.2.

### ISSUE THREAD

**Issue by developer-shekhar** [scinfu/SwiftSoup#16]
Showing multiple errors when compiling in the aove mentioned xcode, please correct.

**Comment by scinfu** [comment]
I have no error with `Version 8.3.2 (8E2002)` and `SwiftSoup 1.3.0`
What error do you have?

**Comment by developer-shekhar** [comment]
These are the errors
1. Pods/SwiftSoup/Sources/CombiningEvaluator.swift:48:25: 'init' has already been overridden
2. QueryParser.swift:71:38: Cannot invoke value of type 'CombiningEvaluator.And.Type' with argument list '(Array<Evaluator>)'

**Comment by scinfu** [comment]
I can't reproduce this issue. I creare a new project and there is no issue.
If you use cocoa pods try to update .
