### ISSUE TITLE
Selector!?

### ISSUE THREAD

**Issue by misbell** [scinfu/SwiftSoup#161]
What in the name of all that's holy possessed you to name a class with a reserved word? It's breaking everything in my app.

**Comment by scinfu** [comment]
Use `SwiftSoup.Selector`
Yes, maybe is time to refactor this name.

**Comment by scinfu** [comment]
Try 2.3.2 version.

**Comment by scinfu** [comment]
try pod update
if do not work le me see toy pod file and a strip of your code

**Comment by JOyo246** [comment]
The update didn’t work. Deleting/reinstalling did!

**Comment by scinfu** [comment]
pod update was the solution

**Comment by JOyo246** [comment]
'twas not... i ran pod update. Confirmed I was on the newest version. Cleaned. Built. Error.
