### ISSUE TITLE
How to get text from element without whitespace normalization and trimmed 

### ISSUE THREAD

**Issue by dhanrajbhandari** [scinfu/SwiftSoup#169]
Currently,  element.text() method gives trimmed and whitespace normalised text.
Any other way to get element text without trimmed and whitespace normalised?

**Comment by thanhdiqit** [comment]
Look like in my case. I have filtered TextNode and get original text
```
node.children()
                    .filter {
                        $0.hasText()
                    }
                    .compactMap {
                        print("🚀🚀🚀")
                        print($0.ownText())
                    }
```

**Comment by aehlke** [comment]
@thanhdiqit good except delete `hasText()` as this reintroduces the behavior OP doesn't want (check the source code - it will exclude whitespace text nodes)

**Comment by bozek-lu** [comment]
Is there any option to disable trimming repeated whitespaces?
