### ISSUE TITLE
How to get Title and image from Twitter URLs ?

### ISSUE THREAD

**Issue by rahulvyas** [scinfu/SwiftSoup#173]
Does anyone knows how we can parse/get twitter URL's ? for example this URL

`https://twitter.com/Matt_B4DG3R/status/1338441742249504770?s=20`

I'm not able to get anything from this while Facebook parses it properly. Attached Facebook screenshot

![Screenshot 2020-12-14 at 6 32 43 PM](https://user-images.githubusercontent.com/87060/102084230-dd7e4f80-3e3a-11eb-9fcb-5ef419e5e59b.png)

**Comment by Higher08** [comment]
Twitter don't get page content immediately, it getting it by JS
You can use hidden webview, improve WKNavigationDelegate, load there twitter URL.
 `func webView(_ webView: WKWebView, didFinish navigation: WKNavigation!) {
            webView.evaluateJavaScript("document.getElementsByTagName('html')[0].innerHTML") { (html, error) in
                do {
                    try self.getURL(html)
                } catch {
                    print(error)
                }
            }
            
        }`
Of course no one can guarantee that page loaded, so I advice add delay
`getURL` - function with parameter HTML
It look like this
`func getURL(_ innerHTML: Any?) throws {
            guard let htmlString = innerHTML as? String else {
                return
            }
           let doc = try SwiftSoup.parse(htmlString)
// parsing like usual html

        }`
