### ISSUE TITLE
How to prevent html fragment parsing from wrapping with html tags

### ISSUE THREAD

**Issue by bcardarella** [scinfu/SwiftSoup#180]
If I do the following:

```swift
Parser.parseFragment("<div>Hello, world!</div>", nil, "")
```

I get an resulting fragment with html of:

```html
<html>
  <head></head>
  <body>
    <div>Hello, world!</div>
  </body>
</html>
```

whereas I want to preserve the actual fragment of just : `<div>Hello, world!</div>` and not wrap in additional tags. How best can I go about this?

**Comment by polurezov8** [comment]
Hi @bcardarella 👋🏻
Try to use `var html = try document.body()?.html()` to avoid additional tags wrapping.
