### ISSUE TITLE
Get "#document" element

### ISSUE THREAD

**Issue by swifthing** [scinfu/SwiftSoup#183]
Hello, 

Firstly thank you for this tool, swiftsoup is amazing

I have some question: how to get elements inside "#document" ?

Here in this link https://www.ultimedia.com/default/index/videogeneric/id/q0kxs3r

I want to get the url of the video, but it is inside a "iframe", and inside it there is "#document".

This is how I'm trying :

```
let doc = try? SwiftSoup.parse(contents)
let videoLink = doc.select("video#player-player_html5_api").attr("src")
```

But videoLink is empty ...

Can you help me ?

**Comment by scinfu** [comment]
try to print the result and see if there is an attribute src
