### ISSUE TITLE
Can't find SwiftSoup Swift Package

### ISSUE THREAD

**Issue by 0xMarK** [scinfu/SwiftSoup#184]
I tried to find this exact project using the Swift Package list in UI of Xcode 12.4 but didn't find scinfu/SwiftSoup. But I found the mzying2013/SwiftSoup. The problem is that I can't install that one. I get the error:

> because no versions of SwiftSoup match the requirement 1.0.0..<2.0.0 and root depends on SwiftSoup 1.0.0..<2.0.0, version solving failed.

For more info see: https://github.com/mzying2013/SwiftSoup/issues/1

**Comment by scinfu** [comment]
@0xMarK with last version is solved
