### ISSUE TITLE
Thread 1: Fatal error: Index out of range

### ISSUE THREAD

**Issue by SiuyuenChow** [scinfu/SwiftSoup#189]
Occasionally crashes occur when you are constantly pulling HTML data and parsing it with SwiftSoup
Thread 1: Fatal error: Index out of range

Element.swift

Crash code location:
/ * *
* Elements RandomAccessCollection
* /
extension Elements: RandomAccessCollection {
public subscript(position: Int) -> Element {
return this[position]    ------------------------------------->  crash
}

public var startIndex: Int {
return this.startIndex
}

public var endIndex: Int {
return this.endIndex
}

/// The number of Element objects in the collection.
/// Equivalent to `size()`
public var count: Int {
return this.count
}
}

**Comment by scinfu** [comment]
can you share an HTML?
