### ISSUE TITLE
Help with decoding hexadecimal strings in HTML

### ISSUE THREAD

**Issue by SwapnanilDhol** [scinfu/SwiftSoup#190]
\x3Cstyle\x3E\x0A\x20\x20\x20.mainDiv\x0A\x20\x20\

I have a string like that being returned in from the HTML I'm trying to parse. Is there a way to convert that into HTML syntax using this library?

Thank you

**Comment by MuhammedZakir** [comment]
I don't think so. You will probably have to write a function which converts hexadecimal string before parsing.
