### ISSUE TITLE
Crash on codepointsForName

### ISSUE THREAD

**Issue by EthisDF** [scinfu/SwiftSoup#193]
Hello, 

I have this crash in my Xcode Organizer : 
<img width="734" alt="image" src="https://user-images.githubusercontent.com/10416325/131462316-4060425c-7524-4b1f-9579-b8ff23f3b4d6.png">

Is this crash known by SwiftSoup team ? I don't know the html file parsed, but maybe this code can be protected to prevent crash ?

**Comment by jeffersonsetiawan** [comment]
My guess is related to multiple thread want to write to the `static var multipoints`

**Comment by jeffersonsetiawan** [comment]
related to https://github.com/scinfu/SwiftSoup/issues/181

**Comment by scinfu** [comment]
Solved
