### ISSUE TITLE
ITMS-90496: Invalid Executable 

### ISSUE THREAD

**Issue by jpeinadoc** [scinfu/SwiftSoup#199]
I have xcode 13, and when trying to archive the app an error occurs

ITMS-90496: Invalid Executable - The executable '***** app / Watch / **** WatchKit App.app/PlugIns/**** WatchKit Extension.appex / ***** WatchKit Extension' does not contain bitcode.

The weird thing is that it passes the validations without problems, but when I want to upload to the store the error occurs

**Comment by AlexanderPan** [comment]
It's work for me: https://developer.apple.com/forums/thread/690934
