### ISSUE TITLE
Parse process never finished for real we sites

### ISSUE THREAD

**Issue by shvets** [scinfu/SwiftSoup#2]
Example:

import Just
import SwiftSoup

let url: String = "http://comcast.net"
let response: HTTPResult = Just.get(url)
let data: Data = response.content
let html = String(data: data!, encoding: String.Encoding.utf8)

do {
  let doc: Document = try SwiftSoup.parse(html!)
  print(try doc.text())
}
catch {
  print("Error")
}

It never prints anything, just runs forever

**Comment by scinfu** [comment]
The problem was CharacterReader in a function very slow.
Now is resolved .
#3

**Comment by scinfu** [comment]
Thank you for reporting.
I close this the issue , if needed reopen.
