### ISSUE TITLE
Swift 5.5.2

### ISSUE THREAD

**Issue by mdecaro** [scinfu/SwiftSoup#200]
Can't load package since updating Xcode to latest (13.2) using the PackageManager.  When I try to load the package it hangs on  'Preparing to validate'.

To complicate matters when I tried cocoa pods, that app crashed!!

Any workarounds?

**Comment by cfristrom** [comment]
This seems to be an issue with the 13.2 App Store install, the workaround at the moment is to download the .xib from developer.apple.com.

**Comment by mdecaro** [comment]
Thanks, that worked.
