### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by dragonsKnight5** [scinfu/SwiftSoup#202]
Any chance of generating official documentation for SwiftSoup?

When I search for it in google I come across this [link](http://cocoadocs.org/docsets/SwiftSoup/1.2.0) which appears to be broken, I'm not sure about 
how to generate it myself since all examples detailing this process that I've come across so far involve 
xcode and macOS whereas I'm using Linux(Fedora)

Best Regards
dragonsKnight5

**Comment by scinfu** [comment]
Hi @dragonsKnight5 ,
The link you reported is not mine, they are links that external sites generate based on the README.
For SwiftSoup documentation refer to the readme where the main functions of the library are documented.
If you need more examples you can see unit test functions  https://github.com/scinfu/SwiftSoup/tree/master/Tests/SwiftSoupTests

**Comment by dragonsKnight5** [comment]
I know the link isn't yours, I was only mentioning it as a rough supporting reference.

I was hoping there might be documentation provided in a similar format to javadoc for java, I didn't realize that
you were providing it in the root level readme file.

Thank you for clearing that up
