### ISSUE TITLE
Elements eachText missing

### ISSUE THREAD

**Issue by dragonsKnight5** [scinfu/SwiftSoup#203]
Hi,
trying to find eachText function in Elements but it appears to be missing, has this function been
renamed during the porting process of jsoup?

need this function to port my android/java program across to a swift macOS/iOS/Linux program

Best Regards
dragonsKnight5

**Comment by scinfu** [comment]
Hi @dragonsKnight5, this function is never ported, I can do it now, give some time to port it.

**Comment by scinfu** [comment]
Ok, released in 2.3.6

**Comment by dragonsKnight5** [comment]
Thank you for being able to add this in so quickly

Best Regards
dragonsKnight5
