### ISSUE TITLE
how to use SwiftSoup in oc?

### ISSUE THREAD

**Issue by yueyuedede1** [scinfu/SwiftSoup#218]
how to use SwiftSoup in oc?

**Comment by scinfu** [comment]
Sorry, but what do you mean with _**oc**_?

**Comment by Chidorin** [comment]
javascript on/cookie support

I'm new to web stuff, so the question is regarding retrieving price data from https://steamdb.info/app/1063970 by parsing page and looking for key words. But in my case I don't have body data and have messages about turning Javascript on and enabling cookies. Is SwiftSoup a proper tool?

linux, swift-5.6.1-RELEASE

p.s. sorry for not creating a new issue, the button is just grey and I can't push it to create new issue

**Comment by lvyongtao** [comment]
how to use SwiftSoup in objective-c  language

**Comment by scinfu** [comment]
You can't directly, you'll need to create a Wrapper.
SwiftSoup is a pure Swift library, if we add compatibility with Obj-C we lose compatibility with Linux.

```
import SwiftSoup
@objc class Wrapper: NSObject {
    @objc static func parseHTML(html: String) -> String {
        let doc: Document = try! SwiftSoup.parse(html)
        return try! doc.text()
    }
}
```

and

```
#import "ProjectName-Swift.h"
NSString *txt= [Wrapper parseHTML:@"<html></html>"];
```
