### ISSUE TITLE
Thai language characters

### ISSUE THREAD

**Issue by jtcaudill** [scinfu/SwiftSoup#23]
Thai language is not displaying properly in UIWebview.  We are running the html string through SwiftSoup, and the resulting string is manipulating the Thai characters.  Here is the test example I've created:

`"<br>\r\n<br>\r\n<font size=\"2\" face=\"sans-serif\">Lorem Ipsum บังคับ Amet นั่ง, consectetur adipiscing Elit Maecenas หุบเขาญี่ปุ่นเพียงอย่างเดียว ตอนนี้เวลาที่จะลงทุนโปรตีน เสียงนุ่มของสมาชิกในการไว้ทุกข์ VespaCam หุบเขากล่อง การเชื่อมโยงเว็บไซต์ Semper ใน ประสิทธิภาพการทำงานของเส้นผ่าศูนย์กลางใด ๆ แต่การดูแลผู้เล่นฟุตบอลสำนักฟุตบอลสมาร์ทและเรียงลำดับความต้องการ สดนำไปหักลดหย่อนเส้นผ่าศูนย์กลาง ID Ut Libero แต่ละช่วงเวลา lorem ถั่วลิสงได้บังคับ แต่ dui ราคา malesuada แต่ละเครือข่ายแครอทวันหยุดสุดสัปดาห์ ไม่มีน้ำซุปหรือซอส ullamcorper ullamcorper กลัวใครใหญ่กว่าลูกศรสารต้านอนุมูลอิสระ</font>"`

We then take this string and run it through SwiftSoup.parse using this code:

`let originalDocument = try SwiftSoup.parse(testString.replacingOccurrences(of: "\r\n", with: "\n"))`

This is the result output:

`Document <html><head></head><body><br> <br> <font size="2" face="sans-serif">Lorem Ipsum บงคบ Amet นง, consectetur adipiscing Elit Maecenas หบเขาญปนเพยงอยางเดยว ตอนนเวลาทจะลงทนโปรตน เสยงนมของสมาชกในการไวทกข VespaCam หบเขากลอง การเชอมโยงเวบไซต Semper ใน ประสทธภาพการทงานของเสนผาศนยกลางใด ๆ แตการดแลผเลนฟตบอลสนกฟตบอลสมารทและเรยงลดบความตองการ สดนไปหกลดหยอนเสนผาศนยกลาง ID Ut Libero แตละชวงเวลา lorem ถวลสงไดบงคบ แต dui ราคา malesuada แตละเครอขายแครอทวนหยดสดสปดาห ไมมนซปหรอซอส ullamcorper ullamcorper กลวใครใหญกวาลกศรสารตานอนมลอสระ</font></body> </html>`

**Comment by scinfu** [comment]
Hi @jtcaudill thank you for your report.
As we discussed it by email, the error was in the escape of the characters.
Not it's fixed in the pod version 1.4.1(312cb57d66b4d9ff31dbc65043000d88a64918c1), please update and be sure of the right version.

**Comment by jtcaudill** [comment]
Yes, version 1.4.1 fixed the issue.  We were using 1.3.1.
