### ISSUE TITLE
Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7.1 compiler

### ISSUE THREAD

**Issue by sammyfdm** [scinfu/SwiftSoup#231]
I tried to update and build my app and ran into this error:
```
Module compiled with Swift 5.6.1 cannot be imported by the Swift 5.7.1 compiler: .../Build/Products/Release-iphoneos/SwiftSoup.framework/Modules/SwiftSoup.swiftmodule/arm64-apple-ios.swiftmodule
```

I'm using Xcode 14.1 (14B47b). Will you be making a release soon that supports Swift 5.7?

**Comment by sammyfdm** [comment]
Sorry, this turned out to be a problem with Carthage building another dependency and it was failing before building the SwiftSoup xcframework. All good now 👍

**Comment by Sato-Falisa** [comment]
> 抱歉，这原来是 Carthage 构建另一个依赖项的问题，并且在构建 SwiftSoup xcframework 之前失败了。现在一切都好👍

can u share you method？I comfront the same problem and can't deal with it for a long time ,it‘s upset
