### ISSUE TITLE
srcset

### ISSUE THREAD

**Issue by AsareB** [scinfu/SwiftSoup#234]
How is srcset accounted for? The more I search and test the more I think it's just not a thing SwiftSoup can do...

**Comment by scinfu** [comment]
`let myDoc: Document = try SwiftSoup.parse(HTML)
let imgElements: Elements = try myDoc.select("img")
for imgElement in imgElements {
    if let srcset: String = try imgElement.attr("srcset") {
        // process srcset string
    }
}`

You can use regular expressions or string manipulation now
