### ISSUE TITLE
Support for visionOS 

### ISSUE THREAD

**Issue by JustMeDevin** [scinfu/SwiftSoup#246]
Just wondering if there will be plans to update this library to support visionOS?

**Comment by scinfu** [comment]
are you using SPM o cocoapods?

**Comment by JustMeDevin** [comment]
I'm using SPM

**Comment by scinfu** [comment]
Okay, I'll take a look and check what type of errors there are.

**Comment by scinfu** [comment]
Whats is the error do you have with the library?
Are you using SMP or Cocoapods?

**Comment by JustMeDevin** [comment]
It’s working now since the last release to this package. Thanks!

**Comment by medabida** [comment]
Hi, are there any plans to support Carthage as well ? 
when Building with Carthage i get the following error:
```
*** Skipped building SwiftSoup due to the error:
Dependency "SwiftSoup" has no shared framework schemes for any of the platforms: visionOS
```
