### ISSUE TITLE
Leading blank space after parsing

### ISSUE THREAD

**Issue by WBertan** [scinfu/SwiftSoup#26]
Lib version: 1.4.2
Swift 3
iPhone 7 - iOS 10.3

We have the following HTML where after parsing add an extra leading blank space.

HTML: 
`<html><body><div>\r\n<div dir=\"ltr\">\r\n<div id=\"divtagdefaultwrapper\"><font face=\"Calibri,Helvetica,sans-serif\" size=\"3\" color=\"black\"><span style=\"font-size:12pt;\" id=\"divtagdefaultwrapper\">\r\n<div style=\"margin-top:0;margin-bottom:0;\">&nbsp;TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\"><br>\r\n\r\n</div>\r\n<div style=\"margin-top:0;margin-bottom:0;\">TEST</div>\r\n</span></font></div>\r\n</div>\r\n</div>\r\n</body></html>`

Code to parse:
`let doc: Document = try SwiftSoup.parse(contentHtml)`
`var text = try doc.text()`

After parsing:
`"TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n \r\n\r\n\r\n TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n TEST"`

**Comment by WBertan** [comment]
With the lib version 1.3.2 with the same HTML I got this output:
`"TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST"`

**Comment by scinfu** [comment]
Hi, sorry for my delay.
Current master version do not have this problem and the output is:
`"TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST"`
if you use cocoapod, you will need to link using pod 'SwiftSoup', :git => 'https://github.com/scinfu/SwiftSoup.git'.

I can't push a this version in cocoa pods because its compatible only with Swift 3.2 and 4, I'm waiting for new xCode 9 .

**Comment by WBertan** [comment]
Hi, if the output is:

`"TEST TEST TEST TEST TEST TEST TEST TEST TEST TEST"`

it is still wrong. by the HTML the output should be 

`" TEST\r\nTEST\r\nTEST\r\n\r\nTEST\r\nTEST\r\nTEST\r\n\r\n\r\nTEST\r\nTEST\r\nTEST\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\nTEST"`

but I'm getting

`"TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n \r\n\r\n\r\n TEST\r\n TEST\r\n TEST\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n \r\n\r\n\r\n TEST"`

Like it is injecting some spaces in the beginning of the lines, plus some extras new lines. (Where for acknowledge, in Android we had the same "injections" of new lines when using MODE_LEGACY in the parsing, but using MODE_COMPACT in the parsing those new lines aren't there anymore.
