### ISSUE TITLE
Privacy Manifest

### ISSUE THREAD

**Issue by cendolinside123** [scinfu/SwiftSoup#262]
From [Apple docs](https://developer.apple.com/support/third-party-SDK-requirements/) :

> Starting in spring 2024, you must include the privacy manifest for any SDK listed below when you submit new apps in App Store Connect that include those SDKs, or when you submit an app update that adds one of the listed SDKs as part of the update. Signatures are also required in these cases where the listed SDKs are used as binary dependencies.

Could you please add a privacy manifest for this library?

**Comment by scinfu** [comment]
Do you know where can i find an example?
This library do not use any data.

**Comment by cendolinside123** [comment]
> Do you know where can i find an example? This library do not use any data.

Actualy I  don't realy know what data need or what apple API that use on this app.

Some Privacy manifest example baybe can be seen on 
https://github.com/cendolinside123/IGListKit/tree/Jan/Privacy-Manifest-Support-Main-Branch

**Comment by cendolinside123** [comment]
and you can check this one; https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by cendolinside123** [comment]
https://github.com/ReactiveX/RxSwift/issues/2567#issuecomment-1911551070

**Comment by takmorgaming** [comment]
we have updated to the latest pod with SwiftSoup (2.7.1). we can see the Privacy Manifest file. The root case is declared wrong format. So we get this error when we generate the privacy report.

<img width="783" alt="Screenshot 2024-03-04 at 12 15 08 in the afternoon" src="https://github.com/scinfu/SwiftSoup/assets/10565045/6fa66ea9-481c-4fd2-b819-c4cb790cd324">

Privacy Manifest is must change to like this

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSPrivacyTracking</key>
	<false/>
	<key>NSPrivacyTrackingDomains</key>
	<array/>
	<key>NSPrivacyCollectedDataTypes</key>
	<array>
	</array>
	<key>NSPrivacyAccessedAPITypes</key>
	<array>
	</array>
</dict>
</plist>

 So the issues is fixed after change like above. COuld you update the code for that?

**Comment by cendolinside123** [comment]
> we have updated to the latest pod with SwiftSoup (2.7.1). we can see the Privacy Manifest file. The root case is declared wrong format. So we get this error when we generate the privacy report.
> 
> <img alt="Screenshot 2024-03-04 at 12 15 08 in the afternoon" width="783" src="https://private-user-images.githubusercontent.com/10565045/309635850-6fa66ea9-481c-4fd2-b819-c4cb790cd324.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzE4MDMsIm5iZiI6MTcwOTUzMTUwMywicGF0aCI6Ii8xMDU2NTA0NS8zMDk2MzU4NTAtNmZhNjZlYTktNDgxYy00ZmQyLWI4MTktYzRjYjc5MGNkMzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA1NTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlMjIzZmM3YzU0YzBkZGNmNjdkZmJhNzBkNDg4OTQ2Y2ZhYTRhZTFjMDQzYjg0N2YxZmZmOTA1YmYzM2UwZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N24442dy0CDlFTI8T0u2bOFdC174RUwKpbqA6YXucXA">
> Privacy Manifest is must change to like this /*
> 
> NSPrivacyTracking NSPrivacyTrackingDomains NSPrivacyCollectedDataTypes NSPrivacyAccessedAPITypes
> */ So the issues is fixed after change like above. COuld you update the code for that?
<img width="940" alt="Screenshot 2024-03-04 at 12 55 03" src="https://github.com/scinfu/SwiftSoup/assets/29350026/7c7152d7-a7dd-450f-b8a8-57c16f2faff7">
like this one?

**Comment by cendolinside123** [comment]
> [takmorgaming](/takmorgaming)

I see, look like XML issue when I generate value

**Comment by cendolinside123** [comment]
> update to like this ![Screenshot 2024-03-04 at 12 59 28 in the afternoon](https://private-user-images.githubusercontent.com/10565045/309645551-d40f7b41-f170-43bf-b92b-3abfb5fdf640.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk1MzI2NTUsIm5iZiI6MTcwOTUzMjM1NSwicGF0aCI6Ii8xMDU2NTA0NS8zMDk2NDU1NTEtZDQwZjdiNDEtZjE3MC00M2JmLWI5MmItM2FiZmI1ZmRmNjQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA0VDA2MDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NzZjNzEyZmEzZmI2MzgzMzdlNzE4MTIwNzE0MTViNDdlOGY0OTM2OTYxN2ViYWEzNWY0MDUwNzlkMjU2M2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GjasTzRs-HkU0mcqnJBXw-DWi6o71oLYoqK184cNel0)

thanks for the report, already do pull request. Waiting the owner to approve

**Comment by kapitoshka438** [comment]
@scinfu I may be wrong but you don't need to add a privacy manifest at all if your library doesn't collect any tracking or non-tracking data and doesn't use any of APIs needed to be describes in the manifest. In other words, if your manifest is empty just don't add it. The latest version 2.7.1 has invalid manifest and I would recommend to just remove it and release the fix.
<img width="691" alt="Снимок экрана 2024-03-15 в 19 53 00" src="https://github.com/scinfu/SwiftSoup/assets/3232401/7c40bb68-56a9-4b20-ac3c-422bcf2afd88">

**Comment by scinfu** [comment]
released in 2.7.2
thank you

**Comment by radu2lupu** [comment]
I got the following error back from Apple. I am on 2.7.5 version of the library. 
<img width="698" alt="image" src="https://github.com/user-attachments/assets/8df2847d-af58-4d4d-a059-be3acae13b81">

**Comment by jonasman** [comment]
Got the same today
