### ISSUE TITLE
Apparent regression in 2.7.3

### ISSUE THREAD

**Issue by DD-P** [scinfu/SwiftSoup#277]
HTML with Javascript containing CDATA and '&&' hangs on parsing. This first occurs with commit fc06146aa4231a11c5c0f1976a800992566e6e7e

A test case modified from [here](https://www.w3schools.com/js/tryit.asp?filename=tryjs_comparison_and) is 

```
import SwiftSoup
import XCTest

class SwiftSoupTests: XCTestCase {
	func testJavaScriptWithCDATA() throws {
		let html = """
			<!DOCTYPE html>
			<html>
			<body>

			<h1>JavaScript Comparison</h1>
			<h2>The && Operator (Logical AND)</h2>
			<p>The && operator returns true if both expressions are true, otherwise it returns false.</p>

			<p id="demo"></p>

			<script>
			<!--//--><![CDATA[//><!--
			let x = 6;
			let y = 3;

			document.getElementById("demo").innerHTML = 
			(x < 10 && y > 1) + "<br>" + 
			(x < 10 && y < 1);
			//--><!]]>
			</script>

			</body>
			</html>
		"""
		_ = try SwiftSoup.parse(html)
	}
}
```

**Comment by aehlke** [comment]
Sorry, that was my regression

I confirm that this test hangs

**Comment by aehlke** [comment]
Minimal test case which hangs:
```
            <!DOCTYPE html>
            <script>
            <!--//-->
            &
            </script>
```

**Comment by aehlke** [comment]
I fixed it in this PR: https://github.com/scinfu/SwiftSoup/pull/276

**Comment by moehrenzahn** [comment]
Hi, I just wanted to quickly say thanks for your efforts to keep this library updated and working. I just ran into this issue on 2.7.3 and am highly relieved that a fix is already available. You are awesome!

**Comment by aehlke** [comment]
@moehrenzahn np, I appreciate the kind words. I'm using it in production for my own app that I've gone full-time on (Manabi Reader https://reader.manabi.io for learning Japanese) and now that I've made it fast enough to continue using, I'll be sticking with it likely for years to come. Can't promise continued stewardship but I'm happy to see through a couple upgrades so far at least.
