### ISSUE TITLE
ITMS-91108: Invalid privacy manifest

### ISSUE THREAD

**Issue by orj** [scinfu/SwiftSoup#286]
I've been shipping SwiftSoup in my app for a little while now and with my latest submission to the App Store using v2.7.1 I got the following warning:

ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “SwiftSoup_SwiftSoup.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation, starting November 12, 2024, all privacy manifests you submit must have valid content. Keys and values in any privacy manifest must be in a valid format. For more details about privacy manifest files, visit: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files and https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/adding_a_privacy_manifest_to_your_app_or_third-party_sdk.

I see that SwiftSoup has a PrivacyInfo.xcprivacy file in its sources which is nice. But it looks like perhaps it isn't valid any more?

Given SwiftSoup shouldn't be collecting any information perhaps you should remove the xcprivacy file from the sources?

SwiftSoup isn't one of the 3rd party SDKs listed in https://developer.apple.com/support/third-party-SDK-requirements/ either (yet).

**Comment by byshb** [comment]
had the same problem

**Comment by ErikKelly** [comment]
I just submitted an update to my app and I was notified of the same issue. Any tips on resolving it? Thanks.

**Comment by ErikKelly** [comment]
I just submitted an update to my app and I was notified of the same issue. Any tips on resolving it? Thanks.

**Comment by sgrgrsn** [comment]
@scinfu I see it's still references in the [Package.swift](https://github.com/scinfu/SwiftSoup/blob/master/Package.swift#L15) and we get a warning about the missing file when integrating SwiftSoup with Tuist.

Could we get it removed from the Package.swift file as well?

**Comment by aehlke** [comment]
@sgrgrsn i merged the removal

**Comment by sgrgrsn** [comment]
> @sgrgrsn i merged the removal

Perfect, thanks! What's the process of getting a new release version out?

**Comment by aehlke** [comment]
@scinfu please add some more maintainers as I'm low on time to contribute back lately. thank you
