### ISSUE TITLE
Does not compile on Linux with Swift 3.2

### ISSUE THREAD

**Issue by 0xTim** [scinfu/SwiftSoup#31]
Works fine on macOS with 3.2, but naturally fails on Linux 😞 

The log is [here](https://travis-ci.org/brokenhandsio/SteamPress/jobs/277983871) but looks like an issue with `Matcher`. I'll try and dig into it when I get a chance

**Comment by scinfu** [comment]
Hi,
Can you try now ? I release a new version

**Comment by 0xTim** [comment]
Still having issues, looks like it can't find `TextCheckingResult` on Linux. My fork of Swift Soup is running on Swift 4 on Linux for CI where you can see the issue:
https://travis-ci.org/brokenhandsio/SwiftSoup/jobs/280312727

**Comment by 0xTim** [comment]
Have PRed the CI changes so you can see the results (I think the build was broken anyway?). Looks like `TextCheckingResult` is `NSTextCheckingResult` on Linux 😒 but you should be able to fix it with something like https://github.com/IBM-Swift/Kitura/blob/master/Sources/Kitura/RouteRegex.swift#L158

**Comment by 0xTim** [comment]
I've updated the PR with changes for Linux for `NSTextCheckingResult.range(at:)` is not available on Linux at the moment so will need to find a workaround

**Comment by 0xTim** [comment]
Hi @scinfu - the #35 PR should hopefully resolve all of the Linux errors. I've also tidied up the tests and added the missing tests to Linux. I've also fixed the Swift 4 warnings, which should resolve #32. Assuming I haven't made any mistakes and the build goes green, you should have a passing build again!

**Comment by 0xTim** [comment]
(Got on issue on iOS - will try and fix!)

**Comment by 0xTim** [comment]
Should be good to go now!

**Comment by 0xTim** [comment]
Works with Swift 4! 😄
