### ISSUE TITLE
Issue related to multiplyWithOverflow' is unavailable: Use multipliedReportingOverflow(by:) instead in the swift 4

### ISSUE THREAD

**Issue by Ashmika** [scinfu/SwiftSoup#33]
Hello

 As I am getting the below issue related to conversion of the swift 3 to swift 4 . So can you please update that to swift 4.

"multiplyWithOverflow' is unavailable: Use multipliedReportingOverflow(by:) instead."

Also please update your code for swift4.

**Comment by scinfu** [comment]
Swift Soup now can compile with Xcode 9, be sure to update your pod or source to 1.5.0.
Master branch was ready.
