### ISSUE TITLE
SwiftSoup in Xcode 9

### ISSUE THREAD

**Issue by MakiCodes** [scinfu/SwiftSoup#34]
Hi there,

I can't import SwiftSoup into my Xcode 9 project.
When typing in "import SwiftSoup" I get the following error: "No such module 'SwiftSoup' and 34 other compiler errors...

Is it planned to update SwiftSoup for Xcode 9? Any time plan when its ready?

**Comment by scinfu** [comment]
Swift Soup now can compile with Xcode 9, be sure to update your pod or source to 1.5.0.
Master branch was ready.
