### ISSUE TITLE
int has no member multipliedReportingOverflow

### ISSUE THREAD

**Issue by snymax** [scinfu/SwiftSoup#38]
I am seeing this error anywhere this method is used throughout swiftsoup. 

just for sake of being thourough this error began after installing tesseract and running the pod update function. 

I removed tesseract and reinstalled and the error was still occuring

I opened a new project

ran pod init
added swifsoup and set package to version 10.3
ran pod install
opened new workspace
attempted to build blank project with just swift soup and am still recieving the same errors

I have completely reinstalled cocoapods, I have cleared my caches, I have attempted to clean the cache however non of this has helped.

if this is user error I am sorry

**Comment by scinfu** [comment]
Maybe you are using an old version of xCode.
Anyhow I make and update and hash value now is generated with XOR. Bee sure to have 1.5.5 version or high.
