### ISSUE TITLE
Error Node.swift

### ISSUE THREAD

**Issue by rarias84** [scinfu/SwiftSoup#40]
'empty' is inaccessible due to 'private' protection level

**Comment by scinfu** [comment]
`private static let empty = ""` is only an empty string.
Why this property make in your app an error?

**Comment by dilaroga** [comment]
Same issue here.
This constant is used outside the Node class scope, in the CustomStringConversible extension. Should be fileprivate.

**Comment by rarias84** [comment]
@scinfu , I have to remove "private" , the error is ('empty' is inaccessible due to 'private' protection level) , how I said

**Comment by scinfu** [comment]
@rarias84 Why are you using this private variable in your code?
In SwiftSoup is used only in Node.swift.

@dilaroga  in SwiftSoup there no class/extension named CustomStringConversible, where do you see it?

**Comment by rarias84** [comment]
@scinfy you don't understand, the error appear in Node.swift I said in the title and the description you have the error. I have to remove private on empty variable from Node.swift

**Comment by dilaroga** [comment]
@scinfu 
in CustomStringConvertible extension in Node.swift

**Comment by scinfu** [comment]
@dilaroga 
try 1.5.6 version

It's strange though, I don't have any error in linux, macos, ios.

**Comment by dilaroga** [comment]
@scinfu Tried 1.5.6, it's working now.

Thanks
