### ISSUE TITLE
Build Failed Xcode 8.3.3

### ISSUE THREAD

**Issue by sabishm** [scinfu/SwiftSoup#42]
Swift build failed with lot of errors.

<a href="https://ibb.co/c32Fnb"><img src="https://preview.ibb.co/hS7gSb/Screen_Shot_2017_11_11_at_2_18_03_PM.png" alt="Screen_Shot_2017_11_11_at_2_18_03_PM" border="0"></a>

**Comment by sabishm** [comment]
Thank you. I manually change all errors. Now it's working fine great work.

**Comment by scinfu** [comment]
Maybe it not a good idea because every update you will change manually all errors.
I suggest you to use pod `'SwiftSoup', '1.5.2'` , pod` 'SwiftSoup', '1.5.7'`
Or update your xCode to 9 and install latest version of SwiftSoup  `pod 'SwiftSoup'`
