### ISSUE TITLE
Sample code throws error

### ISSUE THREAD

**Issue by rsaeks** [scinfu/SwiftSoup#45]
When trying to use the following sample code:

 do{
            let html = "<html><head><title>First parse</title></head>"
                + "<body><p>Parsed HTML into a doc.</p></body></html>"
            let doc: Document = try SwiftSoup.parse(html)
            return try doc.text()
        }catch Exception.Error(let type, let message){
            print(message)
        }catch{
            print("error")
        }

Xcode returns the following error on the return try line:
Unexpected non-void return value in void function

**Comment by scinfu** [comment]
You have a simple function that not return a string , you can remove "return" or make your function return a value of type String like this:

```
func getString()->String
    {
        do{
            let html = "<title>First parse</title>"
            let doc: Document = try SwiftSoup.parse(html)
            return try doc.text()
        }catch{
            print("error")
        }
        return ""
    }
```
