### ISSUE TITLE
Example_ not working

### ISSUE THREAD

**Issue by moh1122** [scinfu/SwiftSoup#51]
Hello
Thanks for the project well i run pod install on example_ and after i run the project nothing appears how can i try it plz help?

**Comment by scinfu** [comment]
Hi,
Sorry but now the example is emply. 
Try with tests to see how tou can do with the library.
As soon i will do a test project.
Thank you

Inviato da iPhone

**Comment by moh1122** [comment]
Thank you for your quick reply,
but how can I try with tests

**Comment by scinfu** [comment]
Download github project and open it. 

Inviato da iPhone

**Comment by moh1122** [comment]
I already did but its a library after i run it it doesnt launch the app

**Comment by 0xTim** [comment]
@moh1122 open up the Xcode project and run `CMD+U` to run the unit tests. It is a library so there is no app to launch
