### ISSUE TITLE
Dynamic library linker warning

### ISSUE THREAD

**Issue by matadan** [scinfu/SwiftSoup#53]
When building an extension that uses SwiftSoup I get a linker warning:

ld: warning: linking against a dylib which is not safe for use in application extensions: /Users/.../Carthage/Build/iOS/SwiftSoup.framework/SwiftSoup

**Comment by matadan** [comment]
I have solved this in PR #85 after asking an Apple engineer in the Technology Lab at WWDC18.

**Comment by scinfu** [comment]
Thank you
