### ISSUE TITLE
How can I joined '\n' with the .text() ?

### ISSUE THREAD

**Issue by mutongs** [scinfu/SwiftSoup#55]
eg:  let html: String = "<p> <span style="font-size:16px;">One one</span> </p>  <p> <span style="color:#333333;font-family:"font-size:16px;background-color:#FFFFFF;">Two two</span><br /> <span style="color:#333333;font-family:"font-size:16px;background-color:#FFFFFF;"> Three three</span><br /> <span style="color:#333333;font-family:"font-size:16px;background-color:#FFFFFF;"> Four four</span>"
let doc: Document = try SwiftSoup.parse(html)
 return try doc.text()
Then, I want to joined '\n' with eath text,  like this "One one \n Two two \n Three three..."
How can I do with it ? Thank you for your reply.

**Comment by scinfu** [comment]
You should look for all the elements you need and join them.
try doc.body()?.childNodes

**Comment by mutongs** [comment]
Thank you for your reply. 
It works.
