### ISSUE TITLE
Is it possible to use SwiftSoup from Obj-C?

### ISSUE THREAD

**Issue by Drarok** [scinfu/SwiftSoup#58]
I'm working on a legacy project that mixes Obj-C and Swift code, and want to replace string matching with SwiftSoup.

I'm pulling in SwiftSoup as a dependency with CocoaPods, and can use it from Swift without issue. Is there a way I can use SwiftSoup in the Obj-C code as well?

**Comment by Drarok** [comment]
I've found a work-around for this – I created a class that will be exposed to Obj-C and used _that_:

```swift
public class EntitiesCompat: NSObject {

    class func escape(_ string: String) -> String {
        return Entities.escape(string)
    }

    class func unescape(_ string: String) -> String? {
        return try? Entities.unescape(string)
    }
}
```

**Comment by scinfu** [comment]
Hi Drarok,
Yes, the only thing that can be done that I know is to create a wrapper.
SwiftSoup is a pure Swift library, if we add compatibility with Obj-C we lose compatibility with Linux.

**Comment by Drarok** [comment]
Ah, I didn't know that. Fair enough, thanks for responding. 👍
