### ISSUE TITLE
Could not cast value of type 'Swift.Optional<SwiftSoup.Element>'

### ISSUE THREAD

**Issue by burf2000** [scinfu/SwiftSoup#59]
I am randomly downloading html pages and using SwiftSoup to parse them (1.6.0)

The odd page just gives me the following

> Could not cast value of type 'Swift.Optional<SwiftSoup.Element>' (0x103049718) to 'SwiftSoup.Element' (0x100b4ded0).
> 2018-02-15 19:21:05.242422+0000 burf[42885:2056856] Could not cast value of type 'Swift.Optional<SwiftSoup.Element>' (0x103049718) to 'SwiftSoup.Element' (0x100b4ded0).

HTML page url "http://policewb.gov.in/"	

Seems to be something in

```
func replaceActiveFormattingElement(_ out: Element, _ input: Element)throws {
        try formattingElements = replaceInQueue(formattingElements as! Array<Element>, out, input)//todo: testare as! non è bello
    }
```

Is there anyway I can handle this issue without it killing my program

**Comment by scinfu** [comment]
Already fixed with last version.
Please update your library to 1.6.1 version

Scinfu

**Comment by burf2000** [comment]
That's awesome, thanks for fixing it!
