### ISSUE TITLE
Change Log

### ISSUE THREAD

**Issue by iwheelbuy** [scinfu/SwiftSoup#60]
Hello! Your framework is popular enough to start logging all changes! This is my favourite [Change Log](https://github.com/ReactiveX/RxSwift/blob/master/CHANGELOG.md) as example. Thanks in advance!

**Comment by scinfu** [comment]
Hi,
Yes this is a good idea!!!

**Comment by scinfu** [comment]
Done in [1.6.3](https://github.com/scinfu/SwiftSoup/tree/1.6.3)
Thank you
