### ISSUE TITLE
Parser crashing when loss of internet connection

### ISSUE THREAD

**Issue by AL3760** [scinfu/SwiftSoup#66]
```
do{
    let url = URL(string: rssLink)!

    DispatchQueue.global(qos: .userInteractive).async {
        //background thread
        do{
            let html = try? String(contentsOf: url)
            do {
                let doc = try? SwiftSoup.parse(html!) //crashes here when loss of internet connection
                do{
                    let element = try doc?.getElementsByTag("p")
                    do{
                        //other code, brackets, and catches
```

So when I was testing I decided to start scrolling through my tableView and immediately turn off the internet and immediately crashes, is there any code that I'm not aware of in SwiftSoup for dealing with this?

**Comment by 0xTim** [comment]
@AL3760 I'm guessing that `html` is optional - you should really use `guard` for this instead of force unwrapping, otherwise you will crash your app
