### ISSUE TITLE
jsoup: Java HTML Parser

### ISSUE THREAD

**Issue by RLovelett** [scinfu/SwiftSoup#68]
This is a pretty obvious port of the the [jsoup: Java HTML Parser](https://jsoup.org) library. While it is a pragmatic approach to get from nothing to something it seems to have [some Java idioms that leak out of this library into the libraries that depend on it](https://github.com/scinfu/SwiftSoup/blob/6e12e9238c4564ddb131d38e87fd87ce0415bdd6/Sources/Attribute.swift#L77-L84).

My question, what is your thought on refactoring and deprecating some of these idioms/methods? Just to be clear, I'm not suggesting you do it alone. I'm interested in helping. I just wanted to know if you'd be interested in reviewing/accepting these changes into this repository, or should I just work on it in a fork?

For some instances:

* [Using `toString` instead of conforming to `CustomStringConvertible`](https://github.com/scinfu/SwiftSoup/blob/6e12e9238c4564ddb131d38e87fd87ce0415bdd6/Sources/Attribute.swift#L86-L92)
* [Using `hashCode()` instead of conforming to `Hashable`](https://github.com/scinfu/SwiftSoup/blob/6e12e9238c4564ddb131d38e87fd87ce0415bdd6/Sources/Attribute.swift#L125-L129)
* [Using the Java port of `StringBuilder`](https://github.com/scinfu/SwiftSoup/blob/6e12e9238c4564ddb131d38e87fd87ce0415bdd6/Sources/StringBuilder.swift)
* The Javadoc format for docs instead of the Swift markdown

Another question, why is everything a `class`? Is it so that it can support `NSCopying`? Is there a particular reason to support `NSCopying`?

**Comment by scinfu** [comment]
Hi @RLovelett,
Yes, this is a porting of Jsoup  and at the bottom of the readme is written
> SwiftSoup was ported to Swift from Java Jsoup library.

Porting it was not done to be released on github but for an internal project, so  I opted for a 1 to 1 porting to have the same code for both iOS and Android projects.

As you can see not only the parts you have indicated are similar to java but many others, I had in mind to fix them and make the code more Swift friendly, including naming convention, and all the potential that gives us Swift, But I've never had time to do it, now I'm very busy trying to improve performance and add the missing part "Connection".
[StringBuilder](https://github.com/scinfu/SwiftSoup/blob/6e12e9238c4564ddb131d38e87fd87ce0415bdd6/Sources/StringBuilder.swift): I'm trying to eliminate this class, it's very slow. do you have any idea?

> Another question, why is everything a class? Is it so that it can support NSCopying? Is there a particular reason to support NSCopying?
No, as I said I did porting 1 to 1.

>  I just wanted to know if you'd be interested in reviewing/accepting these changes into this repository

Yes, sure,help is welcome.

Thank you.

**Comment by RLovelett** [comment]
> Do you prefer to pull request or be a contributor?

Pull request for now. If that's okay with you. Once we get into agreement on direction and things you want to change then maybe we can increase to contributor.

> I'm trying to eliminate this class, it's very slow. do you have any idea?

We'll my first inclination is just to use the built-in `String` appending capabilities. From [the docs on String performance](https://developer.apple.com/documentation/swift/string#2849845) my bet is that, at least at first, we are unlikely to best the performance provided by the low-level [`String` append capabilities](https://developer.apple.com/documentation/swift/string#2891589).

**Comment by RLovelett** [comment]
So one of the things I'm struggling with right now is just whitespace stuff. I'm a bit of nut job when it comes to whitespace normalization. (I know, I know...)

I like to try and make sure my commits/MRs are as small and targeted. I'm struggling with that right now because sometimes Xcode is changing tabs to spaces (or vice versa) and things are getting hard for me to really even get going.

I think my first MR is going to be a whitespace cleanup and to introduce some a [SwiftLint](https://github.com/realm/SwiftLint) configuration. Does that sound like a good idea?

**Comment by scinfu** [comment]
Yes, sounds good. 👌
