### ISSUE TITLE
When a class name has whitespace

### ISSUE THREAD

**Issue by rocxteady** [scinfu/SwiftSoup#76]
Hello,

What if I have a class includes whitespace? How can I select it?

For example: 
`<div class="detail link"> ...`

I can't select it. Is there any special character to add in order to make it work?
Thanks

**Comment by edgarMejia** [comment]
`doc.select("div.detail.link")`

**Comment by josipvukovic** [comment]
Both cases dont work for me, I have this <div class="fb-like fb_iframe_widget"  ....tried with doc.select("div.fb-like-fb_iframe_widget") and doc.select("div.fb-like.fb_iframe_widget")...none of these work, help please?

**Comment by scinfu** [comment]
Try @edgarMejia solution

<div class="detail link">
doc.select("div.detail.link")
