### ISSUE TITLE
Cannot handle new line

### ISSUE THREAD

**Issue by anovoselskyi** [scinfu/SwiftSoup#77]
Lib version: 1.4.2

Code:
`let string = "Text with tags: <br>new line <b>bold</b> \nnew line"`
`let document = try SwiftSoup.parse(htmlString)`
`print(document.text())`

Output:
`Html text with tags: new line bold new line`

Should be something like:
`Html text with tags: new line bold \nnew line`

**Comment by Pirokar** [comment]
Any solution?

**Comment by andrebng** [comment]
No one able to solve this? I have the same problems for p-tags

I looked at the **Element** class. When you use the `.text()` function it trims the text with new lines. Removing the trimmining didn't fix that issue though...

**Comment by Xzot** [comment]
.replacingOccurrences(of: "\n", with: "</br>") will fix it ;)

**Comment by abeazam** [comment]
> `.replacingOccurrences(of: "\n", with: "</br>")` will fix it ;)

Thanks @Xzot shame its needed but glad it worked.
