### ISSUE TITLE
Build errors in new XCode

### ISSUE THREAD

**Issue by droidery** [scinfu/SwiftSoup#8]
A few build errors in the upcoming XCode 8.3 Beta from new Swift.

To check them, install the beta version of XCode from https://developer.apple.com/download/ alongside your normal XCode

<img width="395" alt="upload" src="https://cloud.githubusercontent.com/assets/25188027/22622675/240872e8-eb95-11e6-8966-5f3d7158b459.png">

**Comment by scinfu** [comment]
Fixed cocoa pods version 1.2.0
