### ISSUE TITLE
implement reader view

### ISSUE THREAD

**Issue by sgbasaraner** [scinfu/SwiftSoup#81]
Is it possible for SwiftSoup to parse HTML like Safari's or Firefox's Reader View does?

**Comment by scinfu** [comment]
What do you mean?

**Comment by sgbasaraner** [comment]
https://github.com/mozilla/readability

Something like this. A smart text/article detector built into SwiftSoup.

**Comment by scinfu** [comment]
The answer is i think is yes, looking quickly what it does.
Many function of Readability.js are based to CSS Selectors like ```getElementsByTagName``` , ```setAttribute```, ```removeAttribute``` or ```getElementsByTagName``` and others.
these functions are implemented in SwiftSoup to select o manipulate the document.

So you should make a porting of Readability.js and use SwiftSoup to manipolate and select elements but I can not know if there are any features you need.

**Comment by scinfu** [comment]
SwiftSoup does what JSDOMParser.js does

**Comment by scinfu** [comment]
What does this library do?

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
