### ISSUE TITLE
Static declarations are implicitly 'final'

### ISSUE THREAD

**Issue by calebkleveter** [scinfu/SwiftSoup#86]
Using Swift 4.2, I am getting the following warning in quite a few places (Xcode counts 93):

```
Static declarations are implicitly 'final'; use 'public' instead of 'open'
```

**Comment by jaskierLTD** [comment]
+1

**Comment by heybetzadec** [comment]
+1

**Comment by shuhaodo** [comment]
How to bypass this warning? If I changed it to public, it won't compile

**Comment by scinfu** [comment]
Try 1.7.3 version

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
