### ISSUE TITLE
SSL_ERROR_ZERO_RETURN

### ISSUE THREAD

**Issue by xyzbilal** [scinfu/SwiftSoup#89]
hi,
while I m trying to parse html in https:// web sites Im getting the error that says "
`[BoringSSL] Function boringssl_session_errorlog: line 238 BoringSSL [C1.1:2] [0x7febfa518b10] [boringssl_session_read] SSL_ERROR_ZERO_RETURN(6): operation failed because the connection was cleanly shut down with a close_notify alert`
my parsing code is 
`  guard let url = URL(string: "https://www.afyoneczaciodasi.org/nobetci-eczaneler") else {return}
        do {
            let html = try String.init(contentsOf: url)
            let doc : Document = try SwiftSoup.parse(html)
            print(doc)`

any idea to solve problem

**Comment by scinfu** [comment]
There was be an error with the connection and SSL, unfortunately, SwiftSoup has no networking call.
