### ISSUE TITLE
Carthage builds from `Example` workspace

### ISSUE THREAD

**Issue by luispadron** [scinfu/SwiftSoup#91]
Carthage seems to build the framework from the example project, this due to the fact that Carthage looks for the first available `.xcodeproject/.xcworkspace`.

I had this issue in one of my frameworks, seems like there are two solutions:

1. Archive a build and serve that in your releases this way Carthage doesn't have to build every time.
2. Move the example project into a separate repository/to a playground.

The error:

```bash
*** Building scheme "SwiftSoup-iOS" in SwiftSoup.xcodeproj
*** Building scheme "SwiftSoup" in Example.xcworkspace
```

**Comment by scinfu** [comment]
fixed in 2.2.1.
