### ISSUE TITLE
Count in Unavailable

### ISSUE THREAD

**Issue by StefanWG** [scinfu/SwiftSoup#92]
I installed SwiftSoup and tried to build it but got this error: 'count' is unavailable: there is no universally good answer, see documentation comment for discussion. This occurred multiple times through various SwiftSoup files that I haven't touched. What should I do?

**Comment by scinfu** [comment]
For what class? 
In general I used ```size``` instead ```count```, I should do a refactor to align the syntax.

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
