### ISSUE TITLE
EXC_BAD_ACCESS when building Release but not when Debug

### ISSUE THREAD

**Issue by defeloper** [scinfu/SwiftSoup#93]
I get Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT) when I build Release. I also removed all optimization so this is not a problem.

I get the error when I:
```
let doc: Document = try SwiftSoup.parse(html)
let sort_courses_div: Elements = try doc.getElementsByClass("something")
let e = sort_courses_div.parents()
let som = try e.first()?.html()       // ERROR
```

I also tryed accessing just to find an error :
```
 sort_courses_div.parents().html()
```

and I got an error but in a file Element.swift. This was the function that I got an error with. 
It was also Thread 1: EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
```
private func html2(_ accum: StringBuilder)throws {
        for node in childNodes {
            try node.outerHtml(accum)
        }
    }
```
<img width="835" alt="screen shot 2018-08-17 at 07 10 56" src="https://user-images.githubusercontent.com/29751238/44248939-c0df9780-a1ed-11e8-9764-4a0796dcc979.png">

**Comment by scinfu** [comment]
Hi,
Do you have a sample html code?
Thank you

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
