### ISSUE TITLE
Anchor Text with HyperLink Clickable

### ISSUE THREAD

**Issue by ghousesgb** [scinfu/SwiftSoup#95]
My HTML looks like this <a href="https://www.google.com"> Click Here </a>.
The issue is I can 
either show https://www.google.com using element.attr("href") and
or
show Click Here using element.text()

What I want is to show  "Click Here" and on click on this open https://www.google.com.

**Comment by scinfu** [comment]
I do not understand what you are trying to do.

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
