### ISSUE TITLE
Parsing HTML data and putting it into a tableview

### ISSUE THREAD

**Issue by stanz7** [scinfu/SwiftSoup#99]
Hey guys, so currently I'm trying to parse the MTA website for broken elevators and escalators, I did it in python but was wondering about the swift equivalent? Here is my python code: 

`
import urllib
from bs4 import BeautifulSoup
import csv
url = "https://advisory.mtanyct.info/EEoutage/EEOutageReport.aspx?StationID=All"
page = urllib.request.urlopen(url)
soup = BeautifulSoup(page, "html.parser")
with open('test.csv', 'w') as csv_file:
    writer = csv.writer(csv_file)

    table = soup.find(id = 'ctl00_ContentPlaceHolder1_gvElevator')

    for row in table.find_all('tr'):
        if row.has_attr('class'):

            if any(className in row['class'] for className in ('GridRowStyle','GridAlternatingRowStyle')):

                writer.writerow([i.get_text().strip() for i in row.find_all('td')])
`

How would I do this in Swift?

**Comment by scinfu** [comment]
Here is an untested code

```
func testSoup()throws{
        let h = "<a class=lp href=/lib/14160711/>link text</a>"
        let soup = try SwiftSoup.parse(h)
        let table = try soup.select("ctl00_ContentPlaceHolder1_gvElevator")
        
        for row in try table.select("tr"){
            if row.hasAttr("class") // or row.hasClass('class')?
            {
                //
            }
        }
    }
```

**Comment by scinfu** [comment]
Closed due to inactivity, if necessary re-open.
